services:
  drupal-mysql-lib-unb-ca:
    image: mysql:5.7
    restart: unless-stopped
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    expose:
      - "3306"
    networks:
      - aaslp.lib.unb.ca
    volumes:
      - mysql-data:/var/lib/mysql
  drupal-solr-lib-unb-ca:
    image: ghcr.io/unb-libraries/solr-drupal:8.x-4.x
    restart: unless-stopped
    env_file:
      - ./env/solr.env
    expose:
      - "8983"
    networks:
      - aaslp.lib.unb.ca
    entrypoint:
      - docker-entrypoint-multiple.sh
      - aaslp.lib.unb.ca:/solr-conf
    volumes:
      - solr-data:/opt/solr/server/solr/mycores
  drupal-redis-lib-unb-ca:
    image: redis:5-alpine
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - aaslp.lib.unb.ca
    env_file:
      - ./env/redis.env
  aaslp.lib.unb.ca:
    build:
      context: .
    restart: unless-stopped
    container_name: aaslp.lib.unb.ca
    depends_on:
      - drupal-mysql-lib-unb-ca
      - drupal-solr-lib-unb-ca
      - drupal-redis-lib-unb-ca
    expose:
      - "80"
    networks:
      - aaslp.lib.unb.ca
    ports:
      - "3111:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - drupal-data:/app/html/sites/default
      - ./config-yml:/app/configuration
      - ./custom/modules:/app/html/modules/custom
      - ./custom/themes:/app/html/themes/custom
      - ./tests:/app/tests
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    expose:
      - "1025"
      - "8025"
    ports:
      - "4111:8025"
    networks:
      - aaslp.lib.unb.ca
  cypress:
    image: ghcr.io/unb-libraries/cypress-drupal:10.x-9.x-1.x
    container_name: cypress.aaslp.lib.unb.ca
    depends_on:
      - aaslp.lib.unb.ca
    environment:
      - BASE_URL=http://aaslp.lib.unb.ca
    volumes:
      - ./tests/cypress/default/e2e:/cypress/e2e
    networks:
      - aaslp.lib.unb.ca
networks:
  aaslp.lib.unb.ca:
    name: aaslp.lib.unb.ca
volumes:
  drupal-data:
  mysql-data:
  solr-data:
